\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\LoadClass{school-base}
\ProvidesClass{school-22.312}

\usepackage[version=3]{mhchem}
\usepackage{color}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{mathtools}
\usepackage{graphicx}
\usepackage{grffile}
\usepackage{multirow}
\usepackage{hyperref}

\usepackage{school-style-math}
\usepackage{school-style-units}

\usepackage{school-style-class}
\classcode{22.312}
\schoolname{Massachusetts Institute of Technology}
