\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\LoadClassWithOptions{school-base}
\ProvidesClass{school-22.39}

\usepackage{school-style-class}
\classcode{22.39}
\classname{Reactor Design, Operations and Safety}
\professor{Emilio Baglietto, Vesna B. Dimitrijevic, R.G. Ballinger }
\schoolname{Massachusetts Institute of Technology}

% 2012-02-22.tex, 2012-04-25.tex
\usepackage{caption}
\usepackage{subcaption}
